import '../app/ui/global.css'
import SideNav from './ui/dashboard/sidenav'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <div>  {children}</div>

      </body>
    </html>
  )
}
